/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tapalol;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Gabriel Amorim
 * @author Felipe Toshio
 */

public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    
    public TelaJogo() { 
        getContentPane().setBackground(Color.DARK_GRAY);
        initComponents();
        
        //GridLayout gridChampions = new GridLayout(6,8);
        //jPanelCampeoesContent.setLayout(gridChampions);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCampeoes = new javax.swing.JPanel();
        jPanelCampeoesContent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelSaguao = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelSaguaoContent = new javax.swing.JPanel();
        jPanelTempo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelPontuacaoSolo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelJogadores = new javax.swing.JPanel();
        jPanelJogador1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelIcone1 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                ImageIcon icone1 = new ImageIcon("src/tapalol/icones/iconejogador/Jogador1.png");
                Image i1 = icone1.getImage();

                g.drawImage(i1, 0, 0, this.getSize().width, this.getSize().height, this);
            }

        };
        jPanelJogador2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelIcone2 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                ImageIcon icone1 = new ImageIcon("src/tapalol/icones/iconejogador/Jogador2.png");
                Image i1 = icone1.getImage();

                g.drawImage(i1, 0, 0, this.getSize().width, this.getSize().height, this);

            }

        };
        jPanelJogador3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelIcone3 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                ImageIcon icone1 = new ImageIcon("src/tapalol/icones/iconejogador/Jogador3.png");
                Image i1 = icone1.getImage();

                g.drawImage(i1, 0, 0, this.getSize().width, this.getSize().height, this);

            }

        };
        jPanelJogador4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelIcone4 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                ImageIcon icone1 = new ImageIcon("src/tapalol/icones/iconejogador/Jogador4.png");
                Image i1 = icone1.getImage();

                g.drawImage(i1, 0, 0, this.getSize().width, this.getSize().height, this);

            }

        };
        jPanelEscolhido = new javax.swing.JPanel();
        jPanelCampeaoEscolhido = new javax.swing.JPanel();
        jPanelPontuacao = new javax.swing.JPanel();
        jPanelPontuacaoContent = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tapa LOL");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanelCampeoes.setBackground(new java.awt.Color(1, 42, 168));
        jPanelCampeoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCampeoesContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCampeoesContentLayout = new javax.swing.GroupLayout(jPanelCampeoesContent);
        jPanelCampeoesContent.setLayout(jPanelCampeoesContentLayout);
        jPanelCampeoesContentLayout.setHorizontalGroup(
            jPanelCampeoesContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanelCampeoesContentLayout.setVerticalGroup(
            jPanelCampeoesContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Campeões");

        javax.swing.GroupLayout jPanelCampeoesLayout = new javax.swing.GroupLayout(jPanelCampeoes);
        jPanelCampeoes.setLayout(jPanelCampeoesLayout);
        jPanelCampeoesLayout.setHorizontalGroup(
            jPanelCampeoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCampeoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCampeoesContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelCampeoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCampeoesLayout.setVerticalGroup(
            jPanelCampeoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCampeoesLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCampeoesContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSaguao.setBackground(new java.awt.Color(1, 42, 168));
        jPanelSaguao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Saguão");

        jPanelSaguaoContent.setBackground(new java.awt.Color(149, 164, 209));
        jPanelSaguaoContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelSaguaoContentLayout = new javax.swing.GroupLayout(jPanelSaguaoContent);
        jPanelSaguaoContent.setLayout(jPanelSaguaoContentLayout);
        jPanelSaguaoContentLayout.setHorizontalGroup(
            jPanelSaguaoContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSaguaoContentLayout.setVerticalGroup(
            jPanelSaguaoContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelSaguaoLayout = new javax.swing.GroupLayout(jPanelSaguao);
        jPanelSaguao.setLayout(jPanelSaguaoLayout);
        jPanelSaguaoLayout.setHorizontalGroup(
            jPanelSaguaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaguaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(235, Short.MAX_VALUE))
            .addComponent(jPanelSaguaoContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelSaguaoLayout.setVerticalGroup(
            jPanelSaguaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaguaoLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSaguaoContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTempo.setBackground(new java.awt.Color(149, 164, 209));
        jPanelTempo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Timer");

        javax.swing.GroupLayout jPanelTempoLayout = new javax.swing.GroupLayout(jPanelTempo);
        jPanelTempo.setLayout(jPanelTempoLayout);
        jPanelTempoLayout.setHorizontalGroup(
            jPanelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTempoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelTempoLayout.setVerticalGroup(
            jPanelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTempoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelPontuacaoSolo.setBackground(new java.awt.Color(149, 164, 209));
        jPanelPontuacaoSolo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Score");

        javax.swing.GroupLayout jPanelPontuacaoSoloLayout = new javax.swing.GroupLayout(jPanelPontuacaoSolo);
        jPanelPontuacaoSolo.setLayout(jPanelPontuacaoSoloLayout);
        jPanelPontuacaoSoloLayout.setHorizontalGroup(
            jPanelPontuacaoSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPontuacaoSoloLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelPontuacaoSoloLayout.setVerticalGroup(
            jPanelPontuacaoSoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPontuacaoSoloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanelJogadores.setBackground(new java.awt.Color(1, 42, 168));

        jPanelJogador1.setBackground(new java.awt.Color(149, 164, 209));
        jPanelJogador1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelJogador1.setPreferredSize(new java.awt.Dimension(203, 123));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setText("Jogador 1");

        jPanelIcone1.setPreferredSize(new java.awt.Dimension(65, 52));

        javax.swing.GroupLayout jPanelIcone1Layout = new javax.swing.GroupLayout(jPanelIcone1);
        jPanelIcone1.setLayout(jPanelIcone1Layout);
        jPanelIcone1Layout.setHorizontalGroup(
            jPanelIcone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanelIcone1Layout.setVerticalGroup(
            jPanelIcone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelJogador1Layout = new javax.swing.GroupLayout(jPanelJogador1);
        jPanelJogador1.setLayout(jPanelJogador1Layout);
        jPanelJogador1Layout.setHorizontalGroup(
            jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIcone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelJogador1Layout.setVerticalGroup(
            jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogador1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIcone1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelJogador2.setBackground(new java.awt.Color(149, 164, 209));
        jPanelJogador2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelJogador2.setPreferredSize(new java.awt.Dimension(203, 123));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setText("Jogador 2");

        jPanelIcone2.setPreferredSize(new java.awt.Dimension(65, 52));

        javax.swing.GroupLayout jPanelIcone2Layout = new javax.swing.GroupLayout(jPanelIcone2);
        jPanelIcone2.setLayout(jPanelIcone2Layout);
        jPanelIcone2Layout.setHorizontalGroup(
            jPanelIcone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanelIcone2Layout.setVerticalGroup(
            jPanelIcone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelJogador2Layout = new javax.swing.GroupLayout(jPanelJogador2);
        jPanelJogador2.setLayout(jPanelJogador2Layout);
        jPanelJogador2Layout.setHorizontalGroup(
            jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIcone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJogador2Layout.setVerticalGroup(
            jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelJogador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIcone2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(27, 27, 27))
        );

        jPanelJogador3.setBackground(new java.awt.Color(149, 164, 209));
        jPanelJogador3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel15.setText("Jogador 3");

        jPanelIcone3.setPreferredSize(new java.awt.Dimension(65, 52));

        javax.swing.GroupLayout jPanelIcone3Layout = new javax.swing.GroupLayout(jPanelIcone3);
        jPanelIcone3.setLayout(jPanelIcone3Layout);
        jPanelIcone3Layout.setHorizontalGroup(
            jPanelIcone3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanelIcone3Layout.setVerticalGroup(
            jPanelIcone3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelJogador3Layout = new javax.swing.GroupLayout(jPanelJogador3);
        jPanelJogador3.setLayout(jPanelJogador3Layout);
        jPanelJogador3Layout.setHorizontalGroup(
            jPanelJogador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIcone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJogador3Layout.setVerticalGroup(
            jPanelJogador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogador3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelJogador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIcone3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelJogador4.setBackground(new java.awt.Color(149, 164, 209));
        jPanelJogador4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel11.setText("Jogador 4");

        jPanelIcone4.setPreferredSize(new java.awt.Dimension(65, 52));

        javax.swing.GroupLayout jPanelIcone4Layout = new javax.swing.GroupLayout(jPanelIcone4);
        jPanelIcone4.setLayout(jPanelIcone4Layout);
        jPanelIcone4Layout.setHorizontalGroup(
            jPanelIcone4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanelIcone4Layout.setVerticalGroup(
            jPanelIcone4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelJogador4Layout = new javax.swing.GroupLayout(jPanelJogador4);
        jPanelJogador4.setLayout(jPanelJogador4Layout);
        jPanelJogador4Layout.setHorizontalGroup(
            jPanelJogador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIcone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJogador4Layout.setVerticalGroup(
            jPanelJogador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanelJogador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIcone4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanelJogadoresLayout = new javax.swing.GroupLayout(jPanelJogadores);
        jPanelJogadores.setLayout(jPanelJogadoresLayout);
        jPanelJogadoresLayout.setHorizontalGroup(
            jPanelJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jPanelJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jPanelJogador3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelJogadoresLayout.setVerticalGroup(
            jPanelJogadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanelEscolhido.setBackground(new java.awt.Color(149, 164, 209));
        jPanelEscolhido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCampeaoEscolhido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelCampeaoEscolhidoLayout = new javax.swing.GroupLayout(jPanelCampeaoEscolhido);
        jPanelCampeaoEscolhido.setLayout(jPanelCampeaoEscolhidoLayout);
        jPanelCampeaoEscolhidoLayout.setHorizontalGroup(
            jPanelCampeaoEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        jPanelCampeaoEscolhidoLayout.setVerticalGroup(
            jPanelCampeaoEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelEscolhidoLayout = new javax.swing.GroupLayout(jPanelEscolhido);
        jPanelEscolhido.setLayout(jPanelEscolhidoLayout);
        jPanelEscolhidoLayout.setHorizontalGroup(
            jPanelEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhidoLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jPanelCampeaoEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEscolhidoLayout.setVerticalGroup(
            jPanelEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCampeaoEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPontuacao.setBackground(new java.awt.Color(1, 42, 168));
        jPanelPontuacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelPontuacaoContent.setBackground(new java.awt.Color(149, 164, 209));
        jPanelPontuacaoContent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelPontuacaoContentLayout = new javax.swing.GroupLayout(jPanelPontuacaoContent);
        jPanelPontuacaoContent.setLayout(jPanelPontuacaoContentLayout);
        jPanelPontuacaoContentLayout.setHorizontalGroup(
            jPanelPontuacaoContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        jPanelPontuacaoContentLayout.setVerticalGroup(
            jPanelPontuacaoContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pontuação");

        javax.swing.GroupLayout jPanelPontuacaoLayout = new javax.swing.GroupLayout(jPanelPontuacao);
        jPanelPontuacao.setLayout(jPanelPontuacaoLayout);
        jPanelPontuacaoLayout.setHorizontalGroup(
            jPanelPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPontuacaoContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPontuacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPontuacaoLayout.setVerticalGroup(
            jPanelPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPontuacaoLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPontuacaoContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSaguao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(jPanelPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanelJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelPontuacaoSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jPanelCampeoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelTempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPontuacaoSolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanelCampeoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanelJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSaguao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPontuacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCampeaoEscolhido;
    private javax.swing.JPanel jPanelCampeoes;
    private javax.swing.JPanel jPanelCampeoesContent;
    private javax.swing.JPanel jPanelEscolhido;
    private javax.swing.JPanel jPanelIcone1;
    private javax.swing.JPanel jPanelIcone2;
    private javax.swing.JPanel jPanelIcone3;
    private javax.swing.JPanel jPanelIcone4;
    private javax.swing.JPanel jPanelJogador1;
    private javax.swing.JPanel jPanelJogador2;
    private javax.swing.JPanel jPanelJogador3;
    private javax.swing.JPanel jPanelJogador4;
    private javax.swing.JPanel jPanelJogadores;
    private javax.swing.JPanel jPanelPontuacao;
    private javax.swing.JPanel jPanelPontuacaoContent;
    private javax.swing.JPanel jPanelPontuacaoSolo;
    private javax.swing.JPanel jPanelSaguao;
    private javax.swing.JPanel jPanelSaguaoContent;
    private javax.swing.JPanel jPanelTempo;
    // End of variables declaration//GEN-END:variables
}
